### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [jarulraj/sqlcheck#11]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/jarulraj/sqlcheck/blob/d42d1af1dfa0089506de6b41cfa5ae79003bdb0f/src/main.cpp#L15 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by jarulraj** [comment]
Thanks for sharing this. I would be glad to add it in the near future. 

If you would like to send a PR, that would be even better.

**Comment by jarulraj** [comment]
@elfring Does ac8a9a53 look good to you?
