### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Thavaprakash** [jarulraj/sqlcheck#12]
Getting below error, please guide me to install

```
root:~/var/local# sudo dpkg -i SQLCheck-1.0.5-1.x86_64.deb
dpkg-deb: error: `SQLCheck-1.0.5-1.x86_64.deb' is not a debian format archive
dpkg: error processing archive SQLCheck-1.0.5-1.x86_64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 SQLCheck-1.0.5-1.x86_64.deb

```

**Comment by rkulla** [comment]
The wget link in the README for the .zip file is also wrong and 404s. Looks like there's only this link `https://github.com/jarulraj/sqlcheck/files/1226113/SQLCheck-1.0.5-1.x86_64.zip` for the zip

**Comment by jarulraj** [comment]
@Thavaprakash Can you try to download the debian file again to ensure that it is not partially downloaded/corrupted? 

@rkulla Thanks for pointing it. I have updated the README.

**Comment by Thavaprakash** [comment]
I have downloaded again(No partial download and corrupted), still same error.

I'm using below kernel 

#32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dgary1980** [comment]
try https://github.com/jarulraj/sqlcheck/raw/master/releases/SQLCheck-1.0.5-1.x86_64.deb

instead of 

https://github.com/jarulraj/sqlcheck/blob/master/releases/SQLCheck-1.0.5-1.x86_64.deb

**Comment by jarulraj** [comment]
@Thavaprakash any updates? sorry that it is not working for you.

**Comment by Thavaprakash** [comment]
@jarulraj Sorry for late reply, i followed source code installation method which worked fine. I did not check https://github.com/jarulraj/sqlcheck/raw/master/releases/SQLCheck-1.0.5-1.x86_64.deb.

**Comment by jarulraj** [comment]
Sounds good, will then close this.
