### ISSUE TITLE
MSVCP140D.dll is missing

### ISSUE THREAD

**Issue by abrlam** [jarulraj/sqlcheck#20]
Sorry if this is a novice issue.  I tried to run it on Windows 7 Enterprise (SP1, 64-bit) with MSVC++ 2015 Redistributable (x86, x64) installed but I got this error when I ran it in the command prompt.

"The program can't start because MSVCP140D.dll is missing from your computer.  Try reinstalling the program to fix this problem."

I'm not sure where to go from there.  I'm hoping there's a way to get around it without reinstalling the redistributables.

Thank you.

**Comment by jarulraj** [comment]
Thanks for your patience.

I unfortunately don't have enough expertise to suggest a workaround that does not involve reinstalling the redistributables.

This seems to be the solution for this problem: https://answers.microsoft.com/en-us/windows/forum/windows8_1-files/msvcp140ddll-is-missing-from-your-computer/c253126e-8f11-45d0-828d-8ede40c3126a?auth=1

Good luck with that!

**Comment by dstutz** [comment]
It looks like the "D" version of the DLL is the debug version and the redistributable doesn't install that.  Are you sure you're doing a release build?

**Comment by abrlam** [comment]
I got it working by doing the following:
1. install Visual C++ 2015 Build Tools
1. install Windows 10 SDK
2. include ucrtbased.dll in the application

Additional Information:
https://stackoverflow.com/questions/33743493/why-visual-studio-2015-cant-run-exe-file-ucrtbased-dll
https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/

I agree with @dstutz, replacing with the release version of the DLL file might simplify the setup process.

**Comment by Suleman-Elahi** [comment]
It is still not solved yet .!!!

**Comment by gakowalski** [comment]
I've got this error on Windows 10.

```
C:\Users\grzeg\Downloads> ver 
Microsoft Windows [Version 10.0.17134.523]
```

**Comment by Suleman-Elahi** [comment]
If you place `ucrtbased.dll`, `msvcp140d.dll` and `vcruntime140d.dll` in the same folder where the `sqlcheck.exe` is and it will work like charm.

You can download these from [here](https://file.io/HYqZMk) until a permanent fix is published.

**Comment by milos2** [comment]
Thanks Suleman-Elahi! Your advice works for me. Tahnks!
