### ISSUE TITLE
feature: macOS / homebrew release

### ISSUE THREAD

**Issue by sammcj** [jarulraj/sqlcheck#6]
It would be really great if this could build under macOS and be added to [homebrew](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md).

**Comment by jarulraj** [comment]
Agreed. SQLCheck is written in C++ and uses Cmake. I am not familiar with creating macOS and Windows targets with Cmake. If you have expertise in this space, please do comment or send a PR.

**Comment by phillpafford** [comment]
would also be interested in this

**Comment by jarulraj** [comment]
Thanks for your interest. I have added a `MacOS` release. Can you please check if the instructions are correct?

https://github.com/jarulraj/sqlcheck#macos-dmg

**Comment by dnzprmksz** [comment]
It works @jarulraj, thanks for taking a quick action on the request.

**Comment by jarulraj** [comment]
Awesome, thanks for confirming @dnzprmksz.

**Comment by gwerbin** [comment]
I've added a "Cask" for this to my personal Homebrew "Tap": gwerbin/homebrew-tap

```shell
brew tap gwerbin/tap
brew cask install sqlcheck
```

It installs `bin/sqlcheck` to the Homebrew prefix location (usually `/usr/local/bin`), and installs `libsqlcheck_library.a` to `/usr/local/bin/libsqlcheck.a`. The latter path is hardcoded because I don't know how to get the Homebrew prefix dynamically.

**Comment by sammcj** [comment]
Works nicely @gwerbin, thanks for doing that.

**Comment by jarulraj** [comment]
Added this information in the README.

**Comment by gwerbin** [comment]
Update: I've added a source package as well (called a "Formula"): https://github.com/gwerbin/homebrew-tap/blob/master/Formula/sqlcheck.rb

```shell
brew install gwerbin/tap/sqlcheck                # install latest tag, v1.1
brew install --HEAD gwerbin/tap/sqlcheck  # install latest on master
```

Please do read over the code. These things can be a little opaque to write but are very easy to maintain as long as the build process itself doesn't change.

Thanks for a great tool, hopefully having it on Homebrew will help it spread.

**Comment by gwerbin** [comment]
Can I actually get some insight into why `libsqlcheck_library.a` lives in `bin` and not `lib`? I'm updating the formula and wondering if `libsqlcheck_library.a` really needs to be in the user's `PATH`.
