### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by narayagh** [jarulraj/sqlcheck#7]
I see that the ZIP x64 release (for Windows) does not contain an executable. How to use it?

**Comment by jarulraj** [comment]
Sorry, currently the ZIP only contains a Linux binary. SQLCheck is written in `C++` and uses `Cmake`. I am not familiar with creating the [Windows target](https://github.com/jarulraj/sqlcheck/blob/master/CMakeLists.txt#L85) with Cmake. If you have expertise in this space, please do comment or send a PR.

**Comment by jarulraj** [comment]
@narayagh I have added support for Windows. Can you following the instructions here:

https://github.com/jarulraj/sqlcheck#windows
